/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.chrisle.netbeans.plugins.nbscratchfile.components.scratchfilecomponent;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.ActionReferences;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.chrisle.netbeans.plugins.nbscratchfile.components.scratchfilecomponent//ScratchFileComponent//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "ScratchFileComponentTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "org.chrisle.netbeans.plugins.nbscratchfile.components.scratchfilecomponent.ScratchFileComponentTopComponent")
@ActionReferences({
        @ActionReference(path = "Menu/Window")
})

@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ScratchFileComponentAction",
        preferredID = "ScratchFileComponentTopComponent"
)
@Messages({
    "CTL_ScratchFileComponentAction=ScratchFileComponent",
    "CTL_ScratchFileComponentTopComponent=ScratchFileComponent Window",
    "HINT_ScratchFileComponentTopComponent=This is a ScratchFileComponent window"
})
public final class ScratchFileTopComponent extends TopComponent {
    public ScratchFileTopComponent() {
        initComponents();
        setName(Bundle.CTL_ScratchFileComponentTopComponent());
        setToolTipText(Bundle.HINT_ScratchFileComponentTopComponent());
    }

    public void setMimeType(String mimeType) {
        scratchEditor.setContentType(mimeType);
//        scratchEditor.setEditorKit(CloneableEditorSupport.getEditorKit(mimeType));

//        scratchEditor.getAccessibleContext().setAccessibleName("scratchEditor");
//        scratchEditor.getAccessibleContext().setAccessibleDescription(mimeType);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        scratchEditor = new javax.swing.JEditorPane();

        jScrollPane2.setViewportView(scratchEditor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane scratchEditor;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
